<?php

declare(strict_types=1);

namespace Modules\Notifications\Infrastructure\Providers;

use Closure;
use Illuminate\Contracts\Support\DeferrableProvider;
use Illuminate\Support\ServiceProvider;
use Modules\Notifications\Api\NotificationFacadeInterface;
use Modules\Notifications\Application\Facades\NotificationFacade;
use Modules\Notifications\Infrastructure\Drivers\DummyDriver;

final class NotificationServiceProvider extends ServiceProvider implements DeferrableProvider
{
    public function booted(Closure $callback)
    {
        parent::booted($callback); // TODO: Change the autogenerated stub
    }


    public function register(): void
    {
        $this->app->scoped(NotificationFacadeInterface::class, NotificationFacade::class);

        $this->app->singleton(NotificationFacade::class, static fn($app) => new NotificationFacade(
            driver: $app->make(DummyDriver::class),
        ));

        $this->loadRoutesFrom(__DIR__ . '/../../Presentation/routes.php');
    }

    /** @return array<class-string> */
    public function provides(): array
    {
        return [
            NotificationFacadeInterface::class,
        ];
    }
}
